<?php

/**
 * @file
 * Contains featured_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function featured_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the featured_content module.
    case 'help.page.featured_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Featured Content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function featured_content_theme() {
  return [
    'freatured_content_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'block__views_view__front_services__default' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
	
	
  ];
}
